### ISSUE TITLE
build-index.html

### ISSUE THREAD

**Issue by RJPerry23d** [FannyFour/adopt-a-pup#1]
Build the index.html page and start making up the structure of the web app

**Comment by ghost** [comment]
Tonight RJ and I altered the html styling to where it is responsive. Tomorrow we need to start configuring IDs to work with the JS code. Will need status update from Myself Jon and Steve on out JS

**Comment by ghost** [comment]
Thanks RJ looks great

**Comment by RJPerry23d** [comment]
Updated the initial div in add to describe the app and to give simple instructions.
